---

- name: Install apt key
  apt_key: keyserver=keyserver.ubuntu.com id=E56151BF

- name: Detect Linux distro
  shell: "lsb_release -is | tr '[:upper:]' '[:lower:]'"
  register: distro
- debug: var=distro.stdout

- name: Detect Linux code name
  shell: "lsb_release -cs"
  register: codename
- debug: var=codename.stdout

- name: Add mesosphere repository
  apt_repository: repo="deb http://repos.mesosphere.com/{{ distro.stdout }} {{ codename.stdout }} main" state=present

- name: Add Java8 repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  sudo: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Java 8
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - oracle-java8-installer