---

box_name: "ubuntu/trusty64"

providers:
  # VirtualBox
  virtualbox:
    enable: true
  # Amazone EC2 (not implemented)
  ec2:
    enable: false
    access_key_id:  EDIT_HERE
    secret_access_key: EDIT_HERE
    region: us-east-1
    security_groups: EDIT_HERE
    instance_type: m1.small
    keypair_name: EDIT_HERE
    ssh_private_key_path: EDIT_HERE

servers:
  ## Master hosts
  - name: "master-1"
    box: "ubuntu/trusty64"
    cpu: 1
    ram: 512
    ip: 172.17.8.101
    role: "master"
    zk_id: 1

  - name: "master-2"
    box: "ubuntu/trusty64"
    cpu: 1
    ram: 512
    ip: 172.17.8.102
    role: "master"
    zk_id: 2

  ## Slave hosts
  - name: "slave-1"
    box: "ubuntu/trusty64"
    cpu: 2
    ram: 2048
    ip: 172.17.8.201
    role: "slave"

